name: Weather Warning API to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' 

    - name: Install dependencies
      run: npm install

    - name: Run tests 
      run: npm run test:unit 

    - name: Build
      run: npm run build 

    - name: Generate deployment package
      run: |
        # Create a zip file containing your application code
        # Beanstalk expects a specific structure.
        # Ensure all necessary files (like package.json, Procfile, etc.) are included.
        zip -r deploy.zip . 

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22 
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APPLICATION_NAME }}
        environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
        version_label: github-action-${{ github.sha }} 
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip 
        wait_for_deployment: true
